# protos hyprland configuration.. why do i even comment this, nobody gives a shit lmao
# i fucking hate my life

monitor = , preferred, auto, 1

$terminal = kitty
$menu = ""

env = XDG_RUNTIME_DIR,/run/user/0
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = LIBGL_ALWAYS_SOFTWARE,1
env = LIBGL_DRIVERS_PATH,/usr/lib/dri
env = LIBSEAT_BACKEND,builtin

input {
    kb_layout = us
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
}

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(89b4fa)
    col.inactive_border = rgb(313244)
    layout = dwindle
}

decoration {
    rounding = 6
    blur {
        enabled = false
    }
    drop_shadow = false
}

animations {
    enabled = false
}

dwindle {
    pseudotile = true
    preserve_split = true
}

debug {
    disable_logs = false
    enable_stdout_logs = true
}

$mod = SUPER

bind = $mod, Return, exec, $terminal
bind = $mod, Q, killactive,
bind = $mod SHIFT, E, exit,
bind = $mod, V, togglefloating,
bind = $mod, F, fullscreen,
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1 
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

exec-once = $terminal
